// Mock data for development without database
import type { Book, BookCopy, Member, Loan, User } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    username: "admin",
    email: "admin@library.com",
    fullName: "Quản trị viên",
    role: "admin",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    username: "librarian",
    email: "librarian@library.com",
    fullName: "Thủ thư",
    role: "librarian",
    createdAt: new Date("2024-01-01"),
  },
]

export const mockBooks: Book[] = [
  {
    id: "1",
    title: "Lập trình JavaScript hiện đại",
    author: "Nguyễn Văn A",
    isbn: "978-604-1-00001-1",
    publisher: "NXB Thông tin và Truyền thông",
    publishYear: 2023,
    category: "Công nghệ thông tin",
    description: "Cuốn sách hướng dẫn lập trình JavaScript từ cơ bản đến nâng cao",
    totalCopies: 5,
    availableCopies: 3,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    title: "Trí tuệ nhân tạo và Machine Learning",
    author: "Trần Thị B",
    isbn: "978-604-1-00002-8",
    publisher: "NXB Khoa học và Kỹ thuật",
    publishYear: 2023,
    category: "Công nghệ thông tin",
    description: "Giới thiệu về AI và các thuật toán Machine Learning phổ biến",
    totalCopies: 3,
    availableCopies: 2,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    title: "Đắc nhân tâm",
    author: "Dale Carnegie",
    isbn: "978-604-1-00003-5",
    publisher: "NXB Tổng hợp TP.HCM",
    publishYear: 2020,
    category: "Kỹ năng sống",
    description: "Nghệ thuật giao tiếp và ứng xử trong cuộc sống",
    totalCopies: 10,
    availableCopies: 7,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "4",
    title: "Sapiens: Lược sử loài người",
    author: "Yuval Noah Harari",
    isbn: "978-604-1-00004-2",
    publisher: "NXB Văn học",
    publishYear: 2022,
    category: "Lịch sử",
    description: "Câu chuyện về sự tiến hóa của loài người từ thời tiền sử đến hiện đại",
    totalCopies: 8,
    availableCopies: 5,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "5",
    title: "Clean Code",
    author: "Robert C. Martin",
    isbn: "978-604-1-00005-9",
    publisher: "NXB Thông tin và Truyền thông",
    publishYear: 2021,
    category: "Công nghệ thông tin",
    description: "Hướng dẫn viết code sạch và dễ bảo trì",
    totalCopies: 4,
    availableCopies: 4,
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },
]

export const mockBookCopies: BookCopy[] = [
  {
    id: "1",
    bookId: "1",
    barcode: "BC001001",
    status: "borrowed",
    location: "Kệ A1",
    condition: "good",
    acquiredDate: new Date("2024-01-15"),
  },
  {
    id: "2",
    bookId: "1",
    barcode: "BC001002",
    status: "available",
    location: "Kệ A1",
    condition: "excellent",
    acquiredDate: new Date("2024-01-15"),
  },
  {
    id: "3",
    bookId: "2",
    barcode: "BC002001",
    status: "borrowed",
    location: "Kệ A2",
    condition: "good",
    acquiredDate: new Date("2024-01-20"),
  },
  {
    id: "4",
    bookId: "3",
    barcode: "BC003001",
    status: "available",
    location: "Kệ B1",
    condition: "fair",
    acquiredDate: new Date("2024-01-10"),
  },
]

export const mockMembers: Member[] = [
  {
    id: "1",
    memberCode: "MEM001",
    fullName: "Lê Văn C",
    email: "levanc@email.com",
    phone: "0901234567",
    address: "123 Đường ABC, Quận 1, TP.HCM",
    dateOfBirth: new Date("2000-05-15"),
    membershipType: "student",
    membershipStatus: "active",
    registrationDate: new Date("2024-01-01"),
    expiryDate: new Date("2025-01-01"),
    maxBorrowLimit: 5,
    currentBorrowCount: 2,
    totalFines: 0,
  },
  {
    id: "2",
    memberCode: "MEM002",
    fullName: "Phạm Thị D",
    email: "phamthid@email.com",
    phone: "0907654321",
    address: "456 Đường XYZ, Quận 3, TP.HCM",
    dateOfBirth: new Date("1995-08-20"),
    membershipType: "teacher",
    membershipStatus: "active",
    registrationDate: new Date("2024-01-05"),
    expiryDate: new Date("2025-01-05"),
    maxBorrowLimit: 10,
    currentBorrowCount: 1,
    totalFines: 0,
  },
  {
    id: "3",
    memberCode: "MEM003",
    fullName: "Hoàng Văn E",
    email: "hoangvane@email.com",
    phone: "0903456789",
    address: "789 Đường DEF, Quận 5, TP.HCM",
    dateOfBirth: new Date("1988-12-10"),
    membershipType: "public",
    membershipStatus: "active",
    registrationDate: new Date("2024-01-10"),
    expiryDate: new Date("2025-01-10"),
    maxBorrowLimit: 3,
    currentBorrowCount: 0,
    totalFines: 15000,
  },
]

export const mockLoans: Loan[] = [
  {
    id: "1",
    memberId: "1",
    bookCopyId: "1",
    bookId: "1",
    borrowDate: new Date("2024-02-01"),
    dueDate: new Date("2024-02-15"),
    status: "active",
    renewalCount: 0,
    maxRenewals: 2,
    fineAmount: 0,
  },
  {
    id: "2",
    memberId: "1",
    bookCopyId: "3",
    bookId: "2",
    borrowDate: new Date("2024-02-05"),
    dueDate: new Date("2024-02-19"),
    status: "active",
    renewalCount: 0,
    maxRenewals: 2,
    fineAmount: 0,
  },
  {
    id: "3",
    memberId: "2",
    bookCopyId: "4",
    bookId: "3",
    borrowDate: new Date("2024-01-20"),
    dueDate: new Date("2024-02-03"),
    status: "overdue",
    renewalCount: 1,
    maxRenewals: 2,
    fineAmount: 25000,
  },
]
